In [22]:
import xml.etree.ElementTree as ET
import xml.etree.ElementTree as ETree

import pandas as pd

In [39]:
pd.options.display.max_rows = 200

In [36]:
# 1. Read the above xml file using xml module specifically xml.etree.ElementTree 
df = pd.read_xml("uni_info.xml") 
df

,uname,location,course,student,total_students
0,Mumbai University,None,None,NaN,NaN
1,None,"Mumbai, India",None,NaN,NaN
2,None,None,Computer Science,NaN,12.0
3,None,None,Electrical Engineering,NaN,12.0
4,None,None,Physics,NaN,12.0
5,None,None,Chemistry,NaN,12.0
6,None,None,Biology,NaN,12.0
7,None,None,Social Science,NaN,12.0
8,None,None,Mathematics,NaN,12.0

In [37]:
#create a df using pandas which will have the columns as follows "Stream", "Name", "Age", "Gender", "Roll_No" 
root = ET.parse("uni_info.xml")

data = []
for stream in root.findall('stream'):
    course = stream.find('course').text
    students = stream.findall('student')
    for student in students:
        name = student.find('name').text
        age = int(student.find('age').text)
        gender = student.find('gender').text
        roll_number = student.find('roll_number').text
        data.append([course, name, age, gender, roll_number])

df = pd.DataFrame(data, columns=['stream', 'name', 'age', 'gender', 'roll_number'])

In [38]:
df

                    stream             name  age  gender roll_number
0         Computer Science       Janlet Doe   20    Male       CS001
1         Computer Science         John Doe   20    Male       CS002
2         Computer Science        Jason Doe   22    Male       CS003
3         Computer Science        Jenny Doe   19  Female       CS004
4         Computer Science          Jan Doe   21  Female       CS005
5         Computer Science      John Smells   23    Male       CS006
6         Computer Science         Jack Doe   23    Male       CS007
7         Computer Science      Jenifer Doe   22  Female       CS008
8         Computer Science       Justin Doe   22    Male       CS009
9         Computer Science        Jolly Doe   20  Female      CS0010
10        Computer Science          Jon Doe   20    Male      CS0011
11        Computer Science       Jane Smith   21  Female       CS012
12  Electrical Engineering      Aarav Patel   20    Male       EE001
13  Electrical Engineering     Advait Desai   20    Male       EE002
14  Electrical Engineering      Akash Singh   22    Male       EE003
15  Electrical Engineering     Aditi Sharma   19  Female       EE004
16  Electrical Engineering       Amrita Das   21  Female       EE005
17  Electrical Engineering       Aman Verma   23    Male       EE006
18  Electrical Engineering     Aniket Gupta   23    Male       EE007
19  Electrical Engineering       Anaya Shah   22  Female       EE008
20  Electrical Engineering  Ankit Choudhary   22    Male       EE009
21  Electrical Engineering     Anisha Joshi   20  Female      EE0010
22  Electrical Engineering      Arjun Patel   20    Male      EE0011
23  Electrical Engineering       Asha Gupta   21  Female       EE012
24                 Physics    Ashish Sharma   20    Male       PH001
25                 Physics      Ayush Patel   20    Male       PH002
26                 Physics  Chaitanya Kumar   22    Male       PH003
27                 Physics       Asha Gupta   19  Female       PH004
28                 Physics  Chaitanya Kumar   21  Female       PH005
29                 Physics      Danish Khan   23    Male       PH006
30                 Physics      Dhruv Gupta   23    Male       PH007
31                 Physics    Deepika Mehta   22  Female       PH008
32                 Physics      Gaurav Jain   22    Male       PH009
33                 Physics       Diya Singh   20  Female      PH0010
34                 Physics      Harsh Patel   20    Male      PH0011
35                 Physics       Isha Verma   21  Female       PH012
36               Chemistry        Jai Mehta   20    Male       CH001
37               Chemistry      Aarav Patel   20    Male       CH002
38               Chemistry     Advait Desai   22    Male       CH003
39               Chemistry        Jenny Doe   19  Female       CH004
40               Chemistry          Jan Doe   21  Female       CH005
41               Chemistry    Ashish Sharma   23    Male       CH006
42               Chemistry         Jack Doe   23    Male       CH007
43               Chemistry      Jenifer Doe   22  Female       CH008
44               Chemistry  Chaitanya Kumar   22    Male       CH009
45               Chemistry       Asha Gupta   20  Female      CH0010
46               Chemistry          Jon Doe   20    Male      CH0011
47               Chemistry       Jane Smith   21  Female       CH012
48                 Biology      Rohan Patel   20    Male        B001
49                 Biology         John Doe   20    Male        B002
50                 Biology      Samir Singh   22    Male        B003
51                 Biology     Simran Reddy   19  Female        B004
52                 Biology    Shreya Sharma   21  Female        B005
53                 Biology   Siddharth Jain   23    Male        B006
54                 Biology     Sourav Mehta   23    Male        B007
55                 Biology      Jenifer Doe   22  Female        B008
56                 Biology       Justin Doe   22    Male        B009
57                 Biology      Tanvi Gupta   20  Female       B0010
58                 Biology          Jon Doe   20    Male       B0011
59                 Biology       Udit Patel   21  Female        B012
60          Social Science         John Doe   20    Male       SS001
61          Social Science         John Doe   20    Male       SS002
62          Social Science        Jason Doe   22    Male       SS003
63          Social Science        Jenny Doe   19  Female       SS004
64          Social Science          Jan Doe   21  Female       SS005
65          Social Science      John Smells   23    Male       SS006
66          Social Science         Jack Doe   23    Male       SS007
67          Social Science      Jenifer Doe   22  Female       SS008
68          Social Science       Justin Doe   22    Male       SS009
69          Social Science        Jolly Doe   20  Female      SS0010
70          Social Science          Jon Doe   20    Male      SS0011
71          Social Science       Jane Smith   21  Female       SS012
72             Mathematics         John Doe   20    Male        M001
73             Mathematics         John Doe   20    Male        M002
74             Mathematics        Jason Doe   22    Male        M003
75             Mathematics        Jenny Doe   19  Female        M004
76             Mathematics          Jan Doe   21  Female        M005
77             Mathematics      John Smells   23    Male        M006
78             Mathematics         Jack Doe   23    Male        M007
79             Mathematics      Jenifer Doe   22  Female        M008
80             Mathematics       Justin Doe   22    Male        M009
81             Mathematics        Jolly Doe   20  Female       M0010
82             Mathematics          Jon Doe   20    Male       M0011
83             Mathematics       Jane Smith   21  Female        M012

In [92]:
#1. Filter this dataframe to find out how many streams has John Doe present in 
df = df.loc[df['name']=='John Doe']
df

              stream      name  age gender roll_number
1   Computer Science  John Doe   20   Male       CS002
49           Biology  John Doe   20   Male        B002
60    Social Science  John Doe   20   Male       SS001
61    Social Science  John Doe   20   Male       SS002
72       Mathematics  John Doe   20   Male        M001
73       Mathematics  John Doe   20   Male        M002

In [60]:
#I.2 Sort the df according to the age of the students 
df.sort_values(['age'])

                    stream             name  age  gender roll_number
39               Chemistry        Jenny Doe   19  Female       CH004
63          Social Science        Jenny Doe   19  Female       SS004
3         Computer Science        Jenny Doe   19  Female       CS004
75             Mathematics        Jenny Doe   19  Female        M004
15  Electrical Engineering     Aditi Sharma   19  Female       EE004
27                 Physics       Asha Gupta   19  Female       PH004
51                 Biology     Simran Reddy   19  Female        B004
58                 Biology          Jon Doe   20    Male       B0011
24                 Physics    Ashish Sharma   20    Male       PH001
25                 Physics      Ayush Patel   20    Male       PH002
57                 Biology      Tanvi Gupta   20  Female       B0010
0         Computer Science       Janlet Doe   20    Male       CS001
48                 Biology      Rohan Patel   20    Male        B001
33                 Physics       Diya Singh   20  Female      PH0010
34                 Physics      Harsh Patel   20    Male      PH0011
46               Chemistry          Jon Doe   20    Male      CH0011
36               Chemistry        Jai Mehta   20    Male       CH001
37               Chemistry      Aarav Patel   20    Male       CH002
45               Chemistry       Asha Gupta   20  Female      CH0010
22  Electrical Engineering      Arjun Patel   20    Male      EE0011
49                 Biology         John Doe   20    Male        B002
82             Mathematics          Jon Doe   20    Male       M0011
60          Social Science         John Doe   20    Male       SS001
1         Computer Science         John Doe   20    Male       CS002
81             Mathematics        Jolly Doe   20  Female       M0010
73             Mathematics         John Doe   20    Male        M002
72             Mathematics         John Doe   20    Male        M001
21  Electrical Engineering     Anisha Joshi   20  Female      EE0010
10        Computer Science          Jon Doe   20    Male      CS0011
9         Computer Science        Jolly Doe   20  Female      CS0010
12  Electrical Engineering      Aarav Patel   20    Male       EE001
13  Electrical Engineering     Advait Desai   20    Male       EE002
69          Social Science        Jolly Doe   20  Female      SS0010
61          Social Science         John Doe   20    Male       SS002
70          Social Science          Jon Doe   20    Male      SS0011
52                 Biology    Shreya Sharma   21  Female        B005
47               Chemistry       Jane Smith   21  Female       CH012
71          Social Science       Jane Smith   21  Female       SS012
76             Mathematics          Jan Doe   21  Female        M005
64          Social Science          Jan Doe   21  Female       SS005
59                 Biology       Udit Patel   21  Female        B012
83             Mathematics       Jane Smith   21  Female        M012
11        Computer Science       Jane Smith   21  Female       CS012
35                 Physics       Isha Verma   21  Female       PH012
16  Electrical Engineering       Amrita Das   21  Female       EE005
4         Computer Science          Jan Doe   21  Female       CS005
40               Chemistry          Jan Doe   21  Female       CH005
28                 Physics  Chaitanya Kumar   21  Female       PH005
23  Electrical Engineering       Asha Gupta   21  Female       EE012
62          Social Science        Jason Doe   22    Male       SS003
14  Electrical Engineering      Akash Singh   22    Male       EE003
68          Social Science       Justin Doe   22    Male       SS009
67          Social Science      Jenifer Doe   22  Female       SS008
74             Mathematics        Jason Doe   22    Male        M003
19  Electrical Engineering       Anaya Shah   22  Female       EE008
20  Electrical Engineering  Ankit Choudhary   22    Male       EE009
8         Computer Science       Justin Doe   22    Male       CS009
26                 Physics  Chaitanya Kumar   22    Male       PH003
55                 Biology      Jenifer Doe   22  Female        B008
79             Mathematics      Jenifer Doe   22  Female        M008
80             Mathematics       Justin Doe   22    Male        M009
50                 Biology      Samir Singh   22    Male        B003
2         Computer Science        Jason Doe   22    Male       CS003
31                 Physics    Deepika Mehta   22  Female       PH008
32                 Physics      Gaurav Jain   22    Male       PH009
38               Chemistry     Advait Desai   22    Male       CH003
44               Chemistry  Chaitanya Kumar   22    Male       CH009
43               Chemistry      Jenifer Doe   22  Female       CH008
56                 Biology       Justin Doe   22    Male        B009
7         Computer Science      Jenifer Doe   22  Female       CS008
78             Mathematics         Jack Doe   23    Male        M007
77             Mathematics      John Smells   23    Male        M006
5         Computer Science      John Smells   23    Male       CS006
42               Chemistry         Jack Doe   23    Male       CH007
66          Social Science         Jack Doe   23    Male       SS007
65          Social Science      John Smells   23    Male       SS006
17  Electrical Engineering       Aman Verma   23    Male       EE006
18  Electrical Engineering     Aniket Gupta   23    Male       EE007
54                 Biology     Sourav Mehta   23    Male        B007
53                 Biology   Siddharth Jain   23    Male        B006
29                 Physics      Danish Khan   23    Male       PH006
30                 Physics      Dhruv Gupta   23    Male       PH007
6         Computer Science         Jack Doe   23    Male       CS007
41               Chemistry    Ashish Sharma   23    Male       CH006

In [57]:
#I.3. Find out what is the total number of Female students in the University 
df['gender'].value_counts()

gender
Male      49
Female    35
Name: count, dtype: int64